### ISSUE TITLE
Update needed.

### ISSUE THREAD

**Issue by itsmimakhtar** [vishwas-r/Web2App#1]
Please update the project according to the latest versions of Android. Thanks

**Comment by vishwas-r** [comment]
The apk generated from this project is working in Android 13

**Comment by itsmimakhtar** [comment]
Hey there!

I need your assistance setting up my app. Can you help me? 

Actually, it worked but the file input is not working. On my website, I have a form that allows user to upload file. That is not working. Also, I want to some links (with target="_blank") to open using a browser and others inside the app.

**Comment by vishwas-r** [comment]
Checkout this [stackoverflow thread](https://stackoverflow.com/q/27009995) (https://stackoverflow.com/q/27009995) that might help you make it work as per your requirements.
