### ISSUE TITLE
File Upload is not working.

### ISSUE THREAD

**Issue by itsmimakhtar** [vishwas-r/Web2App#2]
Actually, it worked but the file input form on the website is not working. On my website, I have a form that allows users to upload files. That is not working. Also, I want some links (with target="_blank") to open using a browser and others inside the app. And it should download file also...

**Comment by vishwas-r** [comment]
The app shared is just to load entire website inside android webview. To allow uploading of files, app should have permission for files & to open links in browser, you will have to override it. Following links will help you in modifying as per your need.

https://karishma-agr1996.medium.com/file-upload-in-webview-android-26c10ff27aee
https://stackoverflow.com/q/27009995
https://stackoverflow.com/a/15423907
